import stylisticPlugin from '@stylistic/eslint-plugin';
import type { TSESLint } from '@typescript-eslint/utils';
import eslintCommentsPlugin from 'eslint-plugin-eslint-comments';
import importPlugin from 'eslint-plugin-import-x';
import jsdocPlugin from 'eslint-plugin-jsdoc';
import promisePlugin from 'eslint-plugin-promise';
import regexpPlugin from 'eslint-plugin-regexp';
import sonarjsPlugin from 'eslint-plugin-sonarjs';
import unicornPlugin from 'eslint-plugin-unicorn';

export default {
  ...{
    'accessor-pairs': ['error', { setWithoutGet: true }],
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'capitalized-comments': [
      'error',
      'always',
      {
        ignoreConsecutiveComments: true,
        ignorePattern: /language=/u.source, // IntelliJ language injection statements
      },
    ],
    'consistent-return': 'error',
    'consistent-this': ['error', '_this'],
    'constructor-super': 'error',
    curly: ['error', 'all'],
    'default-case': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'for-direction': 'error',
    'func-names': ['error', 'as-needed'],
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'getter-return': 'error',
    'global-require': 'error',
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'guard-for-in': 'error',
    'id-denylist': ['error', 'cb', 'ctx', 'e', 'el', 'enc', 'err', 'evt'],
    'lines-between-class-members': 'off', // Moved to Stylistic
    'logical-assignment-operators': ['error', 'always'],
    'max-statements-per-line': 'off', // Moved to Stylistic
    'multiline-comment-style': 'off', // Moved to Stylistic
    'new-cap': 'off', // Cannot differentiate between library-provided and user-defined functions.
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'error',
    'no-bitwise': 'error',
    'no-buffer-constructor': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-constructor-return': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-div-regex': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-function': 'error',
    'no-empty-pattern': ['error', { allowObjectPatternsAsParameters: true }],
    'no-empty-static-block': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-invalid-this': 'error',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': ['error', { allowLoop: true }],
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-loss-of-precision': 'error',
    'no-magic-numbers': 'off', // Too many scenarios it is reasonable yet flagged.
    'no-misleading-character-class': 'error',
    'no-mixed-requires': 'error',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-nested-ternary': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-path-concat': 'error',
    'no-plusplus': 'error',
    'no-process-env': 'error',
    'no-process-exit': 'error',
    'no-promise-executor-return': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-restricted-globals': ['error', 'event'],
    'no-restricted-syntax': ['error', 'WithStatement', "BinaryExpression[operator='in']"],
    'no-return-assign': 'error',
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-setter-return': 'error',
    'no-shadow': ['error', { hoist: 'all' }],
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-underscore-dangle': [
      'error',
      {
        allow: ['_', '_this', '_1', '_2', '_3', '_4', '_5', '_6', '_7', '_8', '_9'],
        allowAfterSuper: true,
        allowAfterThis: true,
        allowAfterThisConstructor: true,
        allowFunctionParams: false,
        allowInArrayDestructuring: false,
        enforceInClassFields: true,
        enforceInMethodNames: true,
      },
    ],
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': 'error',
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': [
      'error',
      {
        argsIgnorePattern: /^_\w*$/u.source,
        caughtErrorsIgnorePattern: /^_\w*$/u.source,
        varsIgnorePattern: /^(_\d*|React)$/u.source,
      },
    ],
    'no-use-before-define': 'error',
    'no-useless-backreference': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'object-shorthand': ['error', 'always', { avoidExplicitReturnArrows: true, avoidQuotes: true }],
    'one-var': ['error', 'never'],
    'operator-assignment': 'error',
    'padding-line-between-statements': 'off', // Moved to Stylistic
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'off', // Sometimes it's just too much.
    'prefer-exponentiation-operator': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    radix: 'error',
    'require-atomic-updates': 'error',
    'require-unicode-regexp': 'error',
    'require-yield': 'error',
    'spaced-comment': 'off', // Moved to Stylistic
    'symbol-description': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'vars-on-top': 'error',
    yoda: 'error',
  },

  ...eslintCommentsPlugin.configs.recommended.rules,
  'eslint-comments/no-unused-disable': 'error',
  'eslint-comments/require-description': 'error',

  ...importPlugin.configs.recommended.rules,
  'import-x/consistent-type-specifier-style': ['error', 'prefer-top-level'],
  'import-x/first': ['error'],
  'import-x/newline-after-import': 'error',
  'import-x/no-absolute-path': 'error',
  'import-x/no-amd': 'error',
  'import-x/no-anonymous-default-export': [
    'error',
    { allowArray: true, allowCallExpression: true, allowLiteral: true, allowNew: true, allowObject: true },
  ],
  'import-x/no-commonjs': 'error',
  'import-x/no-cycle': ['error', { ignoreExternal: true }],
  'import-x/no-duplicates': 'error',
  'import-x/no-dynamic-require': 'error',
  'import-x/no-empty-named-blocks': 'error',
  'import-x/no-extraneous-dependencies': 'error',
  'import-x/no-mutable-exports': 'error',
  'import-x/no-named-as-default-member': 'off', // Overbearing
  'import-x/no-named-default': 'error',
  'import-x/no-self-import': 'error',
  'import-x/no-unresolved': ['error', { caseSensitiveStrict: true }],
  'import-x/no-unused-modules': 'error',
  'import-x/no-useless-path-segments': 'error',
  'import-x/no-webpack-loader-syntax': 'error',
  'import-x/order': [
    'error',
    {
      alphabetize: { caseInsensitive: true, order: 'asc', orderImportKind: 'asc' },
      groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
      named: true,
      'newlines-between': 'always',
      pathGroups: [
        /* eslint-disable sort-keys -- Logically ordered */
        { pattern: /^pkg:/u.source, group: 'external' },
        { pattern: /^#/u.source, group: 'internal' },
        /* eslint-enable sort-keys -- Logically ordered */
      ],
    },
  ],
  'import-x/prefer-default-export': 'off', // Causes friction when creating a utilities file with a single export in advance of adding additional exports.

  ...jsdocPlugin.configs.recommended.rules,
  'jsdoc/check-indentation': 'error',
  'jsdoc/check-param-names': ['error', { checkDestructured: false }],
  'jsdoc/check-syntax': 'error',
  'jsdoc/match-description': ['error', { matchDescription: '[A-Z]', tags: { param: true, returns: true } }],
  'jsdoc/no-bad-blocks': 'error',
  'jsdoc/no-defaults': 'error',
  'jsdoc/require-asterisk-prefix': 'error',
  'jsdoc/require-jsdoc': 'off',
  'jsdoc/require-param': [
    'error',
    {
      checkConstructors: false,
      checkDestructured: false,
      ignoreWhenAllParamsMissing: true,
    },
  ],
  'jsdoc/require-returns': 'off',
  'jsdoc/sort-tags': 'error',
  'jsdoc/tag-lines': ['error', 'any', { startLines: 1 }],

  ...promisePlugin.configs.recommended.rules,
  'promise/always-return': ['error', { ignoreAssignmentVariable: ['globalThis', 'window'], ignoreLastCallback: true }],
  'promise/no-multiple-resolved': 'error',

  ...regexpPlugin.configs.recommended.rules,
  'regexp/hexadecimal-escape': ['error', 'never'],
  'regexp/letter-case': 'error',
  'regexp/no-empty-character-class': 'error',
  'regexp/no-extra-lookaround-assertions': 'error',
  'regexp/no-misleading-capturing-group': 'error',
  'regexp/no-misleading-unicode-character': 'error',
  'regexp/no-missing-g-flag': 'error',
  'regexp/no-octal': 'error',
  'regexp/no-standalone-backslash': 'error',
  'regexp/prefer-escape-replacement-dollar-char': 'error',
  'regexp/prefer-named-backreference': 'error',
  'regexp/prefer-named-replacement': 'error',
  'regexp/prefer-quantifier': 'error',
  'regexp/prefer-result-array-groups': 'error',
  'regexp/unicode-escape': 'error',
  'regexp/use-ignore-case': 'error',

  ...sonarjsPlugin.configs.recommended.rules,
  'sonarjs/cognitive-complexity': 'off',
  'sonarjs/function-return-type': 'off', // Overly restrictive.
  'sonarjs/max-switch-cases': 'off',
  'sonarjs/no-inverted-boolean-check': 'error',
  'sonarjs/no-nested-template-literals': 'off',
  'sonarjs/no-selector-parameter': 'off', // Overly restrictive.
  'sonarjs/no-small-switch': 'off',
  'sonarjs/prefer-immediate-return': 'off',
  'sonarjs/prefer-read-only-props': 'off', // Too visually noisy.
  'sonarjs/prefer-regexp-exec': 'off',
  'sonarjs/prefer-single-boolean-return': 'off',
  'sonarjs/pseudo-random': 'off', // Gets in the way of basic random usage by assuming everything ever must be cryptographically secure.
  'sonarjs/todo-tag': 'off', // Not everything can be completed immediately.

  ...stylisticPlugin.configs.recommended.rules,
  '@stylistic/arrow-parens': 'off',
  '@stylistic/brace-style': 'off',
  '@stylistic/indent': 'off',
  '@stylistic/indent-binary-ops': 'off',
  '@stylistic/jsx-indent-props': 'off',
  '@stylistic/jsx-one-expression-per-line': 'off',
  '@stylistic/jsx-wrap-multilines': 'off',
  '@stylistic/lines-between-class-members': 'off',
  '@stylistic/max-statements-per-line': 'error',
  '@stylistic/member-delimiter-style': 'off',
  '@stylistic/multiline-comment-style': 'off', // Too frustrating when temporarily commenting out code blocks.
  '@stylistic/multiline-ternary': 'off',
  '@stylistic/no-multiple-empty-line': 'off',
  '@stylistic/operator-linebreak': 'off',
  '@stylistic/padding-line-between-statements': [
    'error',
    /* eslint-disable sort-keys -- Logically ordered */
    { blankLine: 'always', prev: 'directive', next: '*' },
    { blankLine: 'always', prev: 'function', next: 'function' },
    /* eslint-enable sort-keys -- Logically ordered */
  ],
  '@stylistic/quote-props': 'off',
  '@stylistic/quotes': 'off',
  '@stylistic/semi': 'off',
  '@stylistic/spaced-comment': ['error', 'always', { markers: ['/'] }],

  ...unicornPlugin.configs.recommended.rules,
  'unicorn/consistent-function-scoping': ['error', { checkArrowFunctions: false }],
  'unicorn/filename-case': 'off',
  'unicorn/no-null': 'off',
  'unicorn/no-useless-undefined': 'off', // Conflicts with `consistent-return`.
  'unicorn/numeric-separators-style': ['error', { number: { groupLength: 3, minimumDigits: 0 } }],
  'unicorn/prefer-dom-node-text-content': 'off', // `innerText` and `textContent` behave differently so cannot reliably enforce one over the other.
  'unicorn/prefer-event-target': 'error',
  'unicorn/prefer-query-selector': 'off',
  'unicorn/prevent-abbreviations': 'off',
  'unicorn/require-post-message-target-origin': 'error',
  'unicorn/text-encoding-identifier-case': 'off', // Too many false positives
} satisfies TSESLint.FlatConfig.Rules;
