import type { DummyRuleMap } from 'oxlint';

export default {
  'eslint/array-callback-return': 'off',
  'eslint/default-case': 'off',
  'eslint/no-duplicate-imports': 'off',
  'eslint/no-throw-literal': 'off',

  'jsdoc/require-param-type': 'off',
  'jsdoc/require-returns-type': 'off',

  'typescript/adjacent-overload-signatures': 'error',
  'typescript/array-type': 'error',
  'typescript/await-thenable': 'error',
  'typescript/ban-ts-comment': 'error',
  'typescript/class-literal-property-style': 'off',
  'typescript/consistent-indexed-object-style': 'error',
  'typescript/consistent-return': 'error',
  'typescript/consistent-type-assertions': ['error', { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow' }],
  'typescript/consistent-type-definitions': ['error', 'interface'],
  'typescript/consistent-type-exports': ['error', { fixMixedExportsWithInlineTypeSpecifier: true }],
  'typescript/consistent-type-imports': 'error',
  'typescript/dot-notation': 'error',
  'typescript/explicit-function-return-type': [
    'error',
    {
      allowExpressions: true,
      allowFunctionsWithoutTypeParameters: true,
      allowIIFEs: true,
    },
  ],
  'typescript/explicit-module-boundary-types': ['error', { allowArgumentsExplicitlyTypedAsAny: true }],
  'typescript/no-base-to-string': 'error',
  'typescript/no-confusing-non-null-assertion': 'error',
  'typescript/no-confusing-void-expression': 'error',
  'typescript/no-dynamic-delete': 'off',
  'typescript/no-empty-interface': ['error', { allowSingleExtends: true }],
  'typescript/no-empty-object-type': ['error', { allowObjectTypes: 'always' }],
  'typescript/no-explicit-any': 'off',
  'typescript/no-extra-non-null-assertion': 'error',
  'typescript/no-extraneous-class': 'error',
  'typescript/no-floating-promises': 'error',
  'typescript/no-for-in-array': 'error',
  'typescript/no-implied-eval': 'error',
  'typescript/no-inferrable-types': ['error', { ignoreParameters: true }],
  'typescript/no-invalid-void-type': ['error', { allowAsThisParameter: true }],
  'typescript/no-meaningless-void-operator': 'error',
  'typescript/no-misused-new': 'error',
  'typescript/no-misused-promises': 'error',
  'typescript/no-namespace': 'error',
  'typescript/no-non-null-asserted-nullish-coalescing': 'error',
  'typescript/no-non-null-asserted-optional-chain': 'error',
  'typescript/no-non-null-assertion': 'error',
  'typescript/no-require-imports': 'error',
  'typescript/no-this-alias': 'error',
  'typescript/no-unnecessary-boolean-literal-compare': 'error',
  'typescript/no-unnecessary-condition': ['error', { allowConstantLoopConditions: true }],
  'typescript/no-unnecessary-qualifier': 'error',
  'typescript/no-unnecessary-type-arguments': 'error',
  'typescript/no-unnecessary-type-assertion': 'error',
  'typescript/no-unnecessary-type-constraint': 'error',
  'typescript/no-useless-empty-export': 'error',
  'typescript/no-var-requires': 'error',
  'typescript/non-nullable-type-assertion-style': 'error',
  'typescript/only-throw-error': 'error',
  'typescript/prefer-as-const': 'error',
  'typescript/prefer-enum-initializers': 'error',
  'typescript/prefer-for-of': 'error',
  'typescript/prefer-function-type': 'error',
  'typescript/prefer-includes': 'error',
  'typescript/prefer-literal-enum-member': 'error',
  'typescript/prefer-namespace-keyword': 'error',
  'typescript/prefer-nullish-coalescing': [
    'error',
    { ignoreConditionalTests: false, ignoreMixedLogicalExpressions: false },
  ],
  'typescript/prefer-optional-chain': 'error',
  'typescript/prefer-readonly': 'error',
  'typescript/prefer-reduce-type-parameter': 'error',
  'typescript/prefer-return-this-type': 'error',
  'typescript/prefer-string-starts-ends-with': 'error',
  'typescript/prefer-ts-expect-error': 'error',
  'typescript/promise-function-async': 'error',
  'typescript/require-array-sort-compare': 'error',
  'typescript/require-await': 'off',
  'typescript/restrict-plus-operands': 'error',
  'typescript/restrict-template-expressions': 'error',
  'typescript/return-await': 'error',
  'typescript/strict-boolean-expressions': [
    'error',
    {
      allowNullableObject: false,
      allowNullableString: false,
      allowNumber: false,
      allowString: false,
    },
  ],
  'typescript/switch-exhaustiveness-check': [
    'error',
    {
      allowDefaultCaseForExhaustiveSwitch: false,
      considerDefaultExhaustiveForUnions: true,
      requireDefaultForNonUnion: true,
    },
  ],
  'typescript/triple-slash-reference': 'error',
} as const satisfies DummyRuleMap;

export const moduleDeclarations = {
  'eslint/no-duplicate-imports': 'off',
} as const satisfies DummyRuleMap;
