import type { OxlintRules } from '../types.ts';

export default {
  'eslint/accessor-pairs': ['error', { setWithoutGet: true }],
  'eslint/array-callback-return': 'error',
  'eslint/block-scoped-var': 'error',
  'eslint/capitalized-comments': [
    'error',
    'always',
    {
      ignoreConsecutiveComments: true,
      ignorePattern: /language=/u.source,
    },
  ],
  'eslint/consistent-return': 'error',
  'eslint/consistent-this': ['error', '_this'],
  'eslint/constructor-super': 'error',
  'eslint/curly': ['error', 'all'],
  'eslint/default-case': 'error',
  'eslint/default-case-last': 'error',
  'eslint/default-param-last': 'error',
  'eslint/dot-notation': 'error',
  'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
  'eslint/for-direction': 'error',
  'eslint/func-names': ['error', 'as-needed'],
  'eslint/func-style': ['error', 'declaration', { allowArrowFunctions: true }],
  'eslint/getter-return': 'error',
  'eslint/global-require': 'error',
  'eslint/grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'eslint/guard-for-in': 'error',
  'eslint/id-denylist': ['error', ...['cb', 'ctx', 'e', 'el', 'enc', 'err', 'evt', 'req', 'res']],
  'eslint/logical-assignment-operators': ['error', 'always'],
  'eslint/no-alert': 'error',
  'eslint/no-array-constructor': 'error',
  'eslint/no-async-promise-executor': 'error',
  'eslint/no-await-in-loop': 'off', // It is very common to need to process a loop sequentially.
  'eslint/no-bitwise': 'error',
  'eslint/no-caller': 'error',
  'eslint/no-case-declarations': 'error',
  'eslint/no-class-assign': 'error',
  'eslint/no-compare-neg-zero': 'error',
  'eslint/no-cond-assign': 'error',
  'eslint/no-const-assign': 'error',
  'eslint/no-constant-binary-expression': 'error',
  'eslint/no-constant-condition': 'error',
  'eslint/no-constructor-return': 'error',
  'eslint/no-control-regex': 'error',
  'eslint/no-debugger': 'error',
  'eslint/no-delete-var': 'error',
  'eslint/no-div-regex': 'error',
  'eslint/no-dupe-class-members': 'error',
  'eslint/no-dupe-else-if': 'error',
  'eslint/no-dupe-keys': 'error',
  'eslint/no-duplicate-case': 'error',
  'eslint/no-duplicate-imports': 'error',
  'eslint/no-empty': 'error',
  'eslint/no-empty-character-class': 'error',
  'eslint/no-empty-function': 'error',
  'eslint/no-empty-pattern': 'error',
  'eslint/no-empty-static-block': 'error',
  'eslint/no-eval': 'error',
  'eslint/no-ex-assign': 'error',
  'eslint/no-extend-native': 'error',
  'eslint/no-extra-bind': 'error',
  'eslint/no-extra-boolean-cast': 'error',
  'eslint/no-extra-label': 'error',
  'eslint/no-fallthrough': 'error',
  'eslint/no-func-assign': 'error',
  'eslint/no-global-assign': 'error',
  'eslint/no-implicit-coercion': 'error',
  'eslint/no-implicit-globals': 'error',
  'eslint/no-implied-eval': 'error',
  'eslint/no-import-assign': 'error',
  'eslint/no-inner-declarations': 'error',
  'eslint/no-invalid-regexp': 'error',
  'eslint/no-invalid-this': 'error',
  'eslint/no-irregular-whitespace': 'error',
  'eslint/no-iterator': 'error',
  'eslint/no-label-var': 'error',
  'eslint/no-labels': ['error', { allowLoop: true }],
  'eslint/no-lone-blocks': 'error',
  'eslint/no-loop-func': 'error',
  'eslint/no-loss-of-precision': 'error',
  'eslint/no-magic-numbers': 'off', // Too many scenarios it is reasonable yet flagged.
  'eslint/no-misleading-character-class': 'error',
  'eslint/no-multi-assign': 'error',
  'eslint/no-multi-str': 'error',
  'eslint/no-nested-ternary': 'error',
  'eslint/no-new': 'error',
  'eslint/no-new-func': 'error',
  'eslint/no-new-native-nonconstructor': 'error',
  'eslint/no-new-wrappers': 'error',
  'eslint/no-nonoctal-decimal-escape': 'error',
  'eslint/no-obj-calls': 'error',
  'eslint/no-plusplus': 'error',
  'eslint/no-process-env': 'error',
  'eslint/no-process-exit': 'error',
  'eslint/no-promise-executor-return': 'error',
  'eslint/no-proto': 'error',
  'eslint/no-prototype-builtins': 'error',
  'eslint/no-redeclare': 'error',
  'eslint/no-regex-spaces': 'error',
  'eslint/no-restricted-globals': ['error', 'event'],
  'eslint/no-restricted-syntax': ['error', 'WithStatement', "BinaryExpression[operator='in']"],
  'eslint/no-return-assign': 'error',
  'eslint/no-return-await': 'error',
  'eslint/no-script-url': 'error',
  'eslint/no-self-assign': 'error',
  'eslint/no-self-compare': 'error',
  'eslint/no-sequences': 'error',
  'eslint/no-setter-return': 'error',
  'eslint/no-shadow': ['error', { hoist: 'all' }],
  'eslint/no-shadow-restricted-names': 'error',
  'eslint/no-sparse-arrays': 'error',
  'eslint/no-template-curly-in-string': 'error',
  'eslint/no-this-before-super': 'error',
  'eslint/no-throw-literal': 'error',
  'eslint/no-undef': 'error',
  'eslint/no-undef-init': 'error',
  'eslint/no-underscore-dangle': 'off', // Sometimes necessary to have temporarily-unused values.
  'eslint/no-unmodified-loop-condition': 'error',
  'eslint/no-unneeded-ternary': 'error',
  'eslint/no-unreachable': 'error',
  'eslint/no-unreachable-loop': 'error',
  'eslint/no-unsafe-finally': 'error',
  'eslint/no-unsafe-negation': 'error',
  'eslint/no-unsafe-optional-chaining': 'error',
  'eslint/no-unused-expressions': 'error',
  'eslint/no-unused-labels': 'error',
  'eslint/no-unused-private-class-members': 'error',
  'eslint/no-unused-vars': [
    'error',
    {
      argsIgnorePattern: /^_\w*$/u.source,
      caughtErrorsIgnorePattern: /^_\w*$/u.source,
      varsIgnorePattern: /^(_\d*|React)$/u.source,
    },
  ],
  'eslint/no-use-before-define': 'error',
  'eslint/no-useless-backreference': 'error',
  'eslint/no-useless-call': 'error',
  'eslint/no-useless-catch': 'error',
  'eslint/no-useless-computed-key': ['error', { enforceForClassMembers: true }],
  'eslint/no-useless-concat': 'error',
  'eslint/no-useless-constructor': 'error',
  'eslint/no-useless-escape': 'error',
  'eslint/no-useless-rename': 'error',
  'eslint/no-useless-return': 'error',
  'eslint/no-var': 'error',
  'eslint/no-void': 'error',
  'eslint/no-with': 'error',
  'eslint/object-shorthand': ['error', 'always', { avoidExplicitReturnArrows: true, avoidQuotes: true }],
  'eslint/one-var': ['error', 'never'],
  'eslint/operator-assignment': 'error',
  'eslint/prefer-arrow-callback': 'error',
  'eslint/prefer-const': 'error',
  'eslint/prefer-destructuring': 'off', // Sometimes it is just too much.
  'eslint/prefer-exponentiation-operator': 'error',
  'eslint/prefer-numeric-literals': 'error',
  'eslint/prefer-object-spread': 'error',
  'eslint/prefer-promise-reject-errors': 'error',
  'eslint/prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
  'eslint/prefer-rest-params': 'error',
  'eslint/prefer-spread': 'error',
  'eslint/prefer-template': 'error',
  'eslint/radix': 'error',
  'eslint/require-atomic-updates': 'off', // Too many false positives.
  'eslint/require-unicode-regexp': 'error',
  'eslint/require-yield': 'error',
  'eslint/symbol-description': 'error',
  'eslint/use-isnan': 'error',
  'eslint/valid-typeof': 'error',
  'eslint/vars-on-top': 'error',
  'eslint/yoda': 'error',

  'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
  'import/first': 'error',
  'import/no-absolute-path': 'error',
  'import/no-amd': 'error',
  'import/no-anonymous-default-export': [
    'error',
    {
      allowArray: true,
      allowCallExpression: true,
      allowLiteral: true,
      allowNew: true,
      allowObject: true,
    },
  ],
  'import/no-commonjs': 'error',
  'import/no-cycle': ['error', { ignoreExternal: true }],
  'import/no-duplicates': 'error',
  'import/no-dynamic-require': 'error',
  'import/no-empty-named-blocks': 'error',
  'import/no-mutable-exports': 'error',
  'import/no-named-as-default-member': 'off', // Overbearing
  'import/no-named-default': 'error',
  'import/no-self-import': 'error',
  'import/no-useless-path-segments': 'error',
  'import/no-webpack-loader-syntax': 'error',
  // `import/order` – handled by Oxfmt's sortImports
  // `import/no-unresolved` – intentionally not implemented in Oxlint (false positives)
  // `import/newline-after-import` – not yet implemented in Oxlint
  // `import/no-extraneous-dependencies` – not yet implemented in Oxlint
  // `import/no-unused-modules` – not yet implemented in Oxlint
  // `import/prefer-default-export` – intentionally off

  'jsdoc/no-defaults': 'error',
  'jsdoc/require-jsdoc': 'off',
  'jsdoc/require-param': ['error', { checkDestructured: false }],
  'jsdoc/require-returns': 'off',
  // The following jsdoc rules have no Oxlint equivalent and are dropped:
  // check-indentation, check-param-names, check-syntax, match-description,
  // no-bad-blocks, require-asterisk-prefix, sort-tags, tag-lines,
  // no-types, require-param-type, require-returns-type

  'promise/always-return': [
    'error',
    {
      ignoreAssignmentVariable: ['globalThis', 'window'],
      ignoreLastCallback: true,
    },
  ],
  'promise/no-multiple-resolved': 'error',

  'unicorn/catch-error-name': 'off', // A bizarre, overly opinionated rule requiring a non-standard variable name.
  'unicorn/consistent-function-scoping': ['error', { checkArrowFunctions: false }],
  'unicorn/filename-case': 'off',
  'unicorn/no-array-callback-reference': 'off', // Does not perform type inference so incorrectly flags any method matching an inbuilt array method.
  'unicorn/no-array-method-this-argument': 'off', // Does not perform type inference so incorrectly flags any method matching an inbuilt array method.
  'unicorn/no-null': 'off',
  'unicorn/no-useless-undefined': 'off', // Conflicts with consistent-return.
  'unicorn/number-literal-case': 'off', // Conflicts with formatter.
  'unicorn/numeric-separators-style': ['error', { number: { groupLength: 3, minimumDigits: 0 } }],
  'unicorn/prefer-dom-node-text-content': 'off', // `innerText` and `textContent` behave differently so cannot reliably enforce one over the other.
  'unicorn/prefer-event-target': 'error',
  'unicorn/prefer-query-selector': 'off',
  'unicorn/prevent-abbreviations': 'off',
  'unicorn/require-post-message-target-origin': 'error',
  'unicorn/text-encoding-identifier-case': 'off', // Too many false positives.
} as const satisfies OxlintRules;
