import type { DummyRuleMap } from 'oxlint';

export default {
  'jsx-a11y/aria-role': ['error', { allowedInvalidRoles: ['text'] }],
  'jsx-a11y/lang': 'error',
  'jsx-a11y/no-aria-hidden-on-focusable': 'error',
  'jsx-a11y/prefer-tag-over-role': 'error',

  'react/button-has-type': 'error',
  'react/checked-requires-onchange-or-readonly': 'error',
  'react/exhaustive-deps': 'error',
  'react/forward-ref-uses-ref': 'error',
  'react/iframe-missing-sandbox': 'error',
  'react/jsx-boolean-value': ['error', 'always'],
  'react/jsx-curly-brace-presence': ['error', { children: 'never', propElementValues: 'always', props: 'never' }],
  'react/jsx-fragments': ['error', 'syntax'],
  'react/jsx-handler-names': [
    'error',
    {
      checkLocalVariables: true,
      eventHandlerPrefix: /(handle|set|unset|clear|with)/u.source,
    },
  ],
  'react/jsx-key': [
    'error',
    {
      checkFragmentShorthand: true,
      checkKeyMustBeforeSpread: true,
      warnOnDuplicates: true,
    },
  ],
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-script-url': 'error',
  'react/jsx-no-target-blank': 'off',
  'react/jsx-no-useless-fragment': ['error', { allowExpressions: true }],
  'react/jsx-pascal-case': 'error',
  'react/jsx-props-no-spread-multi': 'error',
  'react/no-array-index-key': 'error',
  'react/no-did-mount-set-state': 'error',
  'react/no-namespace': 'error',
  'react/no-redundant-should-component-update': 'error',
  'react/no-set-state': 'error',
  'react/no-this-in-sfc': 'error',
  'react/no-unknown-property': ['error', { requireDataLowercase: true }],
  'react/no-unsafe': 'error',
  'react/no-will-update-set-state': 'error',
  'react/prefer-es6-class': 'error',
  'react/react-in-jsx-scope': 'off',
  'react/self-closing-comp': 'error',
} as const satisfies DummyRuleMap;
